### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by dmitriz** [mjhea0/angular-testing-tutorial#1]
This seems to refer to old node version:

```
 npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.7.4"})
```

Maybe add the packages to the repo, then you won't need to worry about those things and will be less steps for folks to try your repo?

**Comment by mjhea0** [comment]
That's a warning based on the Karma version. I am using the latest [version](https://github.com/karma-runner/karma/releases).

I am also using the latest version of node - 0.12.2. I updated the _package.json_ file to include - `"engines" : { "node" : ">=0.11 <=0.12.2" }`

I'd rather not add the packages since they should really be installed by the end user in order to work properly. I've seen some strange behavior in situations where someone includes the modules. Also, that alert is a warning so it will not affect the actual installing of the dependencies.
